import { PrismaClient, Role, PlanType, TargetApp } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as bcrypt from 'bcrypt';
import 'dotenv/config';

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://postgres:postgrespassword@localhost:5432/smartfeed_db?schema=public';
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Starting database seeding for SmartFeed Studio...');

  const saltRounds = 10;
  const ownerPasswordHash = await bcrypt.hash('adminadmin', saltRounds);

  // ============================================================
  // 1. Seed Dynamic Tariff Plans (STARTER, GROWTH, PRO, ENTERPRISE)
  // ============================================================

  const starterPlan = await prisma.tariffPlan.upsert({
    where: { code: 'STARTER' },
    update: {
      nameUk: 'Старт',
      nameEn: 'Starter',
      descriptionUk: 'Спробуй безкоштовно, без кредитної картки. Відчуй потужність платформи.',
      descriptionEn: 'Try for free, no credit card required. Feel the platform power.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'USD',
      // Quotas
      maxXmlLimit: 500,
      aiCredits: 0,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      maxSuppliersLimit: 1,
      // Feature flags
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      // Display
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 500 SKU товарів',
        '1 постачальник товарів (без мульти-складу)',
        '1 активний XML/CSV фід',
        '1 канал виводу (Rozetka або файл)',
        'Ручне оновлення фіду',
        'Зашифрована локальна SQLite база',
        'Документація та FAQ',
      ],
      featuresEn: [
        'Up to 500 product SKUs',
        '1 product supplier (single source)',
        '1 active XML/CSV feed',
        '1 output channel (Rozetka or file)',
        'Manual feed updates only',
        'Encrypted local SQLite storage',
        'Documentation & FAQ',
      ],
    },
    create: {
      code: 'STARTER',
      nameUk: 'Старт',
      nameEn: 'Starter',
      descriptionUk: 'Спробуй безкоштовно, без кредитної картки. Відчуй потужність платформи.',
      descriptionEn: 'Try for free, no credit card required. Feel the platform power.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'USD',
      maxXmlLimit: 500,
      aiCredits: 0,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      maxSuppliersLimit: 1,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 500 SKU товарів',
        '1 постачальник товарів (без мульти-складу)',
        '1 активний XML/CSV фід',
        '1 канал виводу (Rozetka або файл)',
        'Ручне оновлення фіду',
        'Зашифрована локальна SQLite база',
        'Документація та FAQ',
      ],
      featuresEn: [
        'Up to 500 product SKUs',
        '1 product supplier (single source)',
        '1 active XML/CSV feed',
        '1 output channel (Rozetka or file)',
        'Manual feed updates only',
        'Encrypted local SQLite storage',
        'Documentation & FAQ',
      ],
    },
  });

  const growthPlan = await prisma.tariffPlan.upsert({
    where: { code: 'GROWTH' },
    update: {
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та зосередься на продажах. Для активних продавців.',
      descriptionEn: 'Automate your feeds and focus on sales. For active solo sellers.',
      priceMonthly: 29,
      priceYearly: 290,
      currency: 'USD',
      maxXmlLimit: 10000,
      aiCredits: 50,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 1,
      maxTeamSeats: 1,
      maxSuppliersLimit: 3,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 10,000 SKU товарів',
        'До 3 постачальників (зіставлення прайсів)',
        '5 активних фідів',
        '3 канали виводу (Rozetka, Prom.ua, Google Shopping)',
        'Авто-оновлення 1 раз на добу',
        '50 AI Кредитів на місяць',
        'Хмарний бекап 1 GB (ручний snapshot)',
        'Базова трансформація даних',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 10,000 product SKUs',
        'Up to 3 suppliers (price comparison)',
        '5 active feeds',
        '3 output channels (Rozetka, Prom.ua, Google Shopping)',
        'Auto-sync once per day',
        '50 AI Credits per month',
        '1 GB Cloud backup (manual snapshot)',
        'Basic data transformation rules',
        'Email support within 48h',
      ],
    },
    create: {
      code: 'GROWTH',
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та зосередься на продажах. Для активних продавців.',
      descriptionEn: 'Automate your feeds and focus on sales. For active solo sellers.',
      priceMonthly: 29,
      priceYearly: 290,
      currency: 'USD',
      maxXmlLimit: 10000,
      aiCredits: 50,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 1,
      maxTeamSeats: 1,
      maxSuppliersLimit: 3,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 10,000 SKU товарів',
        'До 3 постачальників (зіставлення прайсів)',
        '5 активних фідів',
        '3 канали виводу (Rozetka, Prom.ua, Google Shopping)',
        'Авто-оновлення 1 раз на добу',
        '50 AI Кредитів на місяць',
        'Хмарний бекап 1 GB (ручний snapshot)',
        'Базова трансформація даних',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 10,000 product SKUs',
        'Up to 3 suppliers (price comparison)',
        '5 active feeds',
        '3 output channels (Rozetka, Prom.ua, Google Shopping)',
        'Auto-sync once per day',
        '50 AI Credits per month',
        '1 GB Cloud backup (manual snapshot)',
        'Basic data transformation rules',
        'Email support within 48h',
      ],
    },
  });

  await prisma.tariffPlan.upsert({
    where: { code: 'PRO' },
    update: {
      nameUk: 'Про',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація фідів з AI — для команд, що масштабуються.',
      descriptionEn: 'Full feed automation with AI — for scaling teams and agencies.',
      priceMonthly: 79,
      priceYearly: 790,
      currency: 'USD',
      maxXmlLimit: 100000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      maxSuppliersLimit: 15,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'До 15 постачальників (авто-зіставлення за EAN/артикулом)',
        'Необмежена кількість фідів',
        '15 каналів виводу (Hotline, Prom.ua, Facebook Catalog і ін.)',
        'Авто-оновлення кожні 4 години',
        '500 AI Кредитів/місяць',
        'Хмарний бекап 10 GB (авто-snapshot щодня)',
        'Розширені правила трансформації',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        '3 місця для команди',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Up to 15 suppliers (auto-matching by EAN/SKU)',
        'Unlimited feeds',
        '15 output channels (Hotline, Prom.ua, Facebook Catalog, etc.)',
        'Auto-sync every 4 hours',
        '500 AI Credits per month',
        '10 GB Cloud backup (daily auto-snapshot)',
        'Advanced transformation rules',
        'Feed version diff comparison',
        'REST API access',
        '3 team seats',
        'Live Chat support within 8h',
      ],
    },
    create: {
      code: 'PRO',
      nameUk: 'Про',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація фідів з AI — для команд, що масштабуються.',
      descriptionEn: 'Full feed automation with AI — for scaling teams and agencies.',
      priceMonthly: 79,
      priceYearly: 790,
      currency: 'USD',
      maxXmlLimit: 100000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      maxSuppliersLimit: 15,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'До 15 постачальників (авто-зіставлення за EAN/артикулом)',
        'Необмежена кількість фідів',
        '15 каналів виводу (Hotline, Prom.ua, Facebook Catalog і ін.)',
        'Авто-оновлення кожні 4 години',
        '500 AI Кредитів/місяць',
        'Хмарний бекап 10 GB (авто-snapshot щодня)',
        'Розширені правила трансформації',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        '3 місця для команди',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Up to 15 suppliers (auto-matching by EAN/SKU)',
        'Unlimited feeds',
        '15 output channels (Hotline, Prom.ua, Facebook Catalog, etc.)',
        'Auto-sync every 4 hours',
        '500 AI Credits per month',
        '10 GB Cloud backup (daily auto-snapshot)',
        'Advanced transformation rules',
        'Feed version diff comparison',
        'REST API access',
        '3 team seats',
        'Live Chat support within 8h',
      ],
    },
  });

  await prisma.tariffPlan.upsert({
    where: { code: 'ENTERPRISE' },
    update: {
      nameUk: 'Корпоратив',
      nameEn: 'Enterprise',
      descriptionUk: 'Корпоративна потужність без enterprise-ціни конкурентів. Для великих мереж.',
      descriptionEn:
        'Enterprise power without competitor enterprise pricing. For large retail networks.',
      priceMonthly: 249,
      priceYearly: 2490,
      currency: 'USD',
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 999999,
      maxTeamSeats: 999999,
      maxSuppliersLimit: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        'Необмежена кількість SKU товарів',
        'Необмежена кількість постачальників (+ API дилерів)',
        'Необмежені фіди та канали виводу',
        'Реальний час оновлення (кожну годину)',
        '5,000 AI Кредитів/місяць + пріоритетна черга',
        'Необмежений хмарний бекап',
        'Власний S3/MinIO ендпоінт клієнта',
        'Необмежені місця для команди',
        'SSO / SAML (Google Workspace, Okta)',
        'Журнал аудиту всіх дій',
        'White-label PDF звіти для клієнтів',
        'REST API + Webhook',
        'Пріоритетна підтримка (Telegram, до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        'Unlimited product SKUs',
        'Unlimited suppliers (+ direct API)',
        'Unlimited feeds and output channels',
        'Near-realtime sync (every hour)',
        '5,000 AI Credits/month + priority queue',
        'Unlimited cloud backup storage',
        'Custom S3/MinIO endpoint',
        'Unlimited team seats',
        'SSO / SAML (Google Workspace, Okta)',
        'Full audit log of all actions',
        'White-label PDF reports for clients',
        'REST API + Webhook push',
        'Priority support (Telegram, within 2h)',
        'SLA 99.9% uptime guarantee',
      ],
    },
    create: {
      code: 'ENTERPRISE',
      nameUk: 'Корпоратив',
      nameEn: 'Enterprise',
      descriptionUk: 'Корпоративна потужність без enterprise-ціни конкурентів. Для великих мереж.',
      descriptionEn:
        'Enterprise power without competitor enterprise pricing. For large retail networks.',
      priceMonthly: 249,
      priceYearly: 2490,
      currency: 'USD',
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 999999,
      maxTeamSeats: 999999,
      maxSuppliersLimit: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        'Необмежена кількість SKU товарів',
        'Необмежена кількість постачальників (+ API дилерів)',
        'Необмежені фіди та канали виводу',
        'Реальний час оновлення (кожну годину)',
        '5,000 AI Кредитів/місяць + пріоритетна черга',
        'Необмежений хмарний бекап',
        'Власний S3/MinIO ендпоінт клієнта',
        'Необмежені місця для команди',
        'SSO / SAML (Google Workspace, Okta)',
        'Журнал аудиту всіх дій',
        'White-label PDF звіти для клієнтів',
        'REST API + Webhook',
        'Пріоритетна підтримка (Telegram, до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        'Unlimited product SKUs',
        'Unlimited suppliers (+ direct API)',
        'Unlimited feeds and output channels',
        'Near-realtime sync (every hour)',
        '5,000 AI Credits/month + priority queue',
        'Unlimited cloud backup storage',
        'Custom S3/MinIO endpoint',
        'Unlimited team seats',
        'SSO / SAML (Google Workspace, Okta)',
        'Full audit log of all actions',
        'White-label PDF reports for clients',
        'REST API + Webhook push',
        'Priority support (Telegram, within 2h)',
        'SLA 99.9% uptime guarantee',
      ],
    },
  });

  // ============================================================
  // 2. Create Single Super Admin (Owner — No customer licenses needed)
  // ============================================================
  const superAdmin = await prisma.user.upsert({
    where: { email: 'admin@admin.com' },
    update: {
      passwordHash: ownerPasswordHash,
      role: Role.SUPER_ADMIN,
      fullName: 'Super Administrator',
    },
    create: {
      email: 'admin@admin.com',
      passwordHash: ownerPasswordHash,
      fullName: 'Super Administrator',
      role: Role.SUPER_ADMIN,
    },
  });

  // Remove any legacy mock admins or dummy licenses
  await prisma.license.deleteMany({
    where: {
      user: { email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] } },
    },
  });
  await prisma.organizationMember.deleteMany({
    where: {
      user: { email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] } },
    },
  });
  await prisma.organization.deleteMany({
    where: {
      id: {
        in: [
          '00000000-0000-0000-0000-000000000000',
          '00000000-0000-0000-0000-000000000001',
          '00000000-0000-0000-0000-000000000002',
        ],
      },
    },
  });
  await prisma.user.deleteMany({
    where: {
      email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] },
    },
  });
  // Super Admin is platform host, delete any customer licenses
  await prisma.license.deleteMany({
    where: { userId: superAdmin.id },
  });

  // ============================================================
  // 5. Seed Dynamic Navigation Items for Desktop & Admin
  // ============================================================
  const navigationItems = [
    {
      key: 'dashboard',
      labelUk: 'Дашборд',
      labelEn: 'Dashboard',
      path: '/',
      icon: 'LayoutDashboard',
      order: 1,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'catalogs',
      labelUk: 'Каталоги товарів',
      labelEn: 'Product Catalogs',
      path: '/catalogs',
      icon: 'Layers',
      order: 2,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'ai_enrichment',
      labelUk: 'AI Збагачення',
      labelEn: 'AI Enrichment',
      path: '/ai-enrichment',
      icon: 'Sparkles',
      order: 3,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'cloud_sync',
      labelUk: 'Хмарна синхронізація',
      labelEn: 'Cloud Sync',
      path: '/cloud-sync',
      icon: 'Cloud',
      order: 4,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'plans',
      labelUk: 'Тарифи',
      labelEn: 'Plans & Pricing',
      path: '/plans',
      icon: 'CreditCard',
      order: 5,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'team',
      labelUk: 'Команда',
      labelEn: 'Team',
      path: '/team',
      icon: 'Users',
      order: 6,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'settings',
      labelUk: 'Налаштування',
      labelEn: 'Settings',
      path: '/settings',
      icon: 'Settings',
      order: 7,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    // ============================================================
    // Admin Portal Navigation Items
    // ============================================================
    {
      key: 'admin_dashboard',
      labelUk: 'Дашборд',
      labelEn: 'Dashboard',
      path: '/',
      icon: 'LayoutDashboard',
      order: 1,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_users',
      labelUk: 'Користувачі',
      labelEn: 'Users',
      path: '/users',
      icon: 'Users',
      order: 2,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_plans',
      labelUk: 'Тарифи',
      labelEn: 'Tariff Plans',
      path: '/plans',
      icon: 'Layers',
      order: 3,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_licenses',
      labelUk: 'Ліцензії',
      labelEn: 'Licenses',
      path: '/licenses',
      icon: 'KeyRound',
      order: 4,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_navigation',
      labelUk: 'Навігація меню',
      labelEn: 'Navigation Menu',
      path: '/navigation',
      icon: 'Compass',
      order: 5,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
  ];

  for (const item of navigationItems) {
    await prisma.navigationItem.upsert({
      where: { key: item.key },
      update: {
        labelUk: item.labelUk,
        labelEn: item.labelEn,
        path: item.path,
        icon: item.icon,
        order: item.order,
        isVisible: item.isVisible,
        requiredRoles: item.requiredRoles,
        requiredPlan: item.requiredPlan,
        targetApp: item.targetApp,
      },
      create: item,
    });
  }

  console.log('✅ Seeding completed:');
  console.log(
    `   - Seeded 4 tariff plans: STARTER ($0), GROWTH ($29), PRO ($79), ENTERPRISE ($249)`,
  );
  console.log(`   - Super Admin: admin@admin.com       (Role: SUPER_ADMIN)`);
  console.log(`   - Seeded ${navigationItems.length} dynamic navigation items`);
  void starterPlan;
  void growthPlan;
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
