import {
  PrismaClient,
  Role,
  PlanType,
  TargetApp,
  PaymentProvider,
} from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as bcrypt from 'bcrypt';
import 'dotenv/config';

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://postgres:postgrespassword@localhost:5432/smartfeed_db?schema=public';
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Starting database seeding for SmartFeed Studio...');

  const saltRounds = 10;
  const ownerPasswordHash = await bcrypt.hash('adminadmin', saltRounds);

  // ============================================================
  // 1. Seed Dynamic Tariff Plans (STARTER, GROWTH, PRO, ENTERPRISE)
  // ============================================================

  const starterPlan = await prisma.tariffPlan.upsert({
    where: { code: 'STARTER' },
    update: {
      nameUk: 'Безкоштовний',
      nameEn: 'Free Trial',
      descriptionUk: 'Спробуй безкоштовно для 1 маркетплейсу. Відчуй швидкість десктопного рушія.',
      descriptionEn: 'Try for free for 1 marketplace of your choice. Feel the speed.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'UAH',
      // Quotas
      maxXmlLimit: 1000,
      aiCredits: 50,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      maxSuppliersLimit: 1,
      // Feature flags
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      // Display
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 1,000 SKU товарів',
        '1 постачальник (базовий прайс)',
        '1 активний фід',
        '1 будь-який канал експорту на вибір (Rozetka, Prom, Google чи кастомний)',
        '50 AI Кредитів на тест',
        'Зашифрована локальна SQLite база',
        'Ручне оновлення',
      ],
      featuresEn: [
        'Up to 1,000 product SKUs',
        '1 product supplier (single price)',
        '1 active feed',
        '1 export channel of choice (Rozetka, Prom, Google or custom)',
        '50 trial AI Credits',
        'Encrypted local SQLite storage',
        'Manual sync',
      ],
    },
    create: {
      code: 'STARTER',
      nameUk: 'Безкоштовний',
      nameEn: 'Free Trial',
      descriptionUk: 'Спробуй безкоштовно для 1 маркетплейсу. Відчуй швидкість десктопного рушія.',
      descriptionEn: 'Try for free for 1 marketplace of your choice. Feel the speed.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'UAH',
      maxXmlLimit: 1000,
      aiCredits: 50,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      maxSuppliersLimit: 1,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 1,000 SKU товарів',
        '1 постачальник (базовий прайс)',
        '1 активний фід',
        '1 будь-який канал експорту на вибір (Rozetka, Prom, Google чи кастомний)',
        '50 AI Кредитів на тест',
        'Зашифрована локальна SQLite база',
        'Ручне оновлення',
      ],
      featuresEn: [
        'Up to 1,000 product SKUs',
        '1 product supplier (single price)',
        '1 active feed',
        '1 export channel of choice (Rozetka, Prom, Google or custom)',
        '50 trial AI Credits',
        'Encrypted local SQLite storage',
        'Manual sync',
      ],
    },
  });

  const growthPlan = await prisma.tariffPlan.upsert({
    where: { code: 'GROWTH' },
    update: {
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та продавай на декількох маркетплейсах одночасно.',
      descriptionEn: 'Automate feeds and sell on multiple marketplaces simultaneously.',
      priceMonthly: 690,
      priceYearly: 6600,
      currency: 'UAH',
      maxXmlLimit: 20000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 2,
      maxTeamSeats: 1,
      maxSuppliersLimit: 3,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 20,000 SKU товарів',
        'До 3 постачальників (порівняння цін та наявності)',
        '5 активних фідів',
        'До 3 каналів експорту одночасно (Rozetka + Prom + Google)',
        'Авто-оновлення 1 раз на добу (24 год)',
        '500 AI Кредитів на місяць',
        'Хмарний бекап 2 GB (до 5 знімків)',
        'Індивідуальні націнки за постачальниками',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 20,000 product SKUs',
        'Up to 3 suppliers (price comparison)',
        '5 active feeds',
        'Up to 3 output channels (Rozetka + Prom + Google)',
        'Auto-sync once per day (24h)',
        '500 AI Credits per month',
        '2 GB Cloud backup (up to 5 snapshots)',
        'Per-supplier markup rules',
        'Email support within 48h',
      ],
    },
    create: {
      code: 'GROWTH',
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та продавай на декількох маркетплейсах одночасно.',
      descriptionEn: 'Automate feeds and sell on multiple marketplaces simultaneously.',
      priceMonthly: 690,
      priceYearly: 6600,
      currency: 'UAH',
      maxXmlLimit: 20000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 2,
      maxTeamSeats: 1,
      maxSuppliersLimit: 3,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 20,000 SKU товарів',
        'До 3 постачальників (порівняння цін та наявності)',
        '5 активних фідів',
        'До 3 каналів експорту одночасно (Rozetka + Prom + Google)',
        'Авто-оновлення 1 раз на добу (24 год)',
        '500 AI Кредитів на місяць',
        'Хмарний бекап 2 GB (до 5 знімків)',
        'Індивідуальні націнки за постачальниками',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 20,000 product SKUs',
        'Up to 3 suppliers (price comparison)',
        '5 active feeds',
        'Up to 3 output channels (Rozetka + Prom + Google)',
        'Auto-sync once per day (24h)',
        '500 AI Credits per month',
        '2 GB Cloud backup (up to 5 snapshots)',
        'Per-supplier markup rules',
        'Email support within 48h',
      ],
    },
  });

  await prisma.tariffPlan.upsert({
    where: { code: 'PRO' },
    update: {
      nameUk: 'Професійний',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація, мульти-склад та командна робота.',
      descriptionEn: 'Full automation, multi-supplier warehouse & team collaboration.',
      priceMonthly: 1490,
      priceYearly: 14280,
      currency: 'UAH',
      maxXmlLimit: 100000,
      aiCredits: 2500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      maxSuppliersLimit: 15,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'До 15 постачальників (авто-зіставлення за EAN/артикулом)',
        'Необмежена кількість фідів',
        'До 15 каналів експорту (+ Kasta, Epicentr, Allo)',
        'Авто-оновлення кожні 4 години',
        '2,500 AI Кредитів на місяць',
        'Хмарний бекап 10 GB + Hub & Spoke синхронізація команди',
        '3 місця для команди (Власник + 2 менеджери)',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        'Договір та акти для юросіб',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Up to 15 suppliers (auto-matching by EAN/SKU)',
        'Unlimited feeds',
        'Up to 15 output channels (+ Kasta, Epicentr, Allo)',
        'Auto-sync every 4 hours',
        '2,500 AI Credits per month',
        '10 GB Cloud backup + Team Hub & Spoke sync',
        '3 team seats (Owner + 2 members)',
        'Feed version diff comparison',
        'REST API access',
        'Invoices & B2B contracts',
        'Live Chat support within 8h',
      ],
    },
    create: {
      code: 'PRO',
      nameUk: 'Професійний',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація, мульти-склад та командна робота.',
      descriptionEn: 'Full automation, multi-supplier warehouse & team collaboration.',
      priceMonthly: 1490,
      priceYearly: 14280,
      currency: 'UAH',
      maxXmlLimit: 100000,
      aiCredits: 2500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      maxSuppliersLimit: 15,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'До 15 постачальників (авто-зіставлення за EAN/артикулом)',
        'Необмежена кількість фідів',
        'До 15 каналів експорту (+ Kasta, Epicentr, Allo)',
        'Авто-оновлення кожні 4 години',
        '2,500 AI Кредитів на місяць',
        'Хмарний бекап 10 GB + Hub & Spoke синхронізація команди',
        '3 місця для команди (Власник + 2 менеджери)',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        'Договір та акти для юросіб',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Up to 15 suppliers (auto-matching by EAN/SKU)',
        'Unlimited feeds',
        'Up to 15 output channels (+ Kasta, Epicentr, Allo)',
        'Auto-sync every 4 hours',
        '2,500 AI Credits per month',
        '10 GB Cloud backup + Team Hub & Spoke sync',
        '3 team seats (Owner + 2 members)',
        'Feed version diff comparison',
        'REST API access',
        'Invoices & B2B contracts',
        'Live Chat support within 8h',
      ],
    },
  });

  await prisma.tariffPlan.upsert({
    where: { code: 'ENTERPRISE' },
    update: {
      nameUk: 'Корпоративний',
      nameEn: 'Enterprise',
      descriptionUk: 'Безлімітна потужність, B2B дилерські прайси та прямий API.',
      descriptionEn: 'Unlimited power, B2B dealer price lists and direct API.',
      priceMonthly: 3990,
      priceYearly: 38280,
      currency: 'UAH',
      maxXmlLimit: 500000,
      aiCredits: 10000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 50,
      maxTeamSeats: 10,
      maxSuppliersLimit: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        '500,000+ SKU (Безліміт товарів)',
        'Необмежена кількість постачальників (+ прямі API дилерів)',
        'Необмежені фіди та канали експорту',
        'Синхронізація щогодини (1 год) або по Webhook',
        '10,000 AI Кредитів/міс + пріоритетна обробка',
        '50 GB сховища + можливість власного S3 (BYOS)',
        '10+ місць для команди (з можливістю розширення)',
        'B2B дилерські прайси та кастомні мапінги',
        'Журнал аудиту дій (Audit Log)',
        'White-label PDF звіти',
        'REST API + Webhooks',
        'Персональний акаунт-менеджер (до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        '500,000+ SKU (Unlimited products)',
        'Unlimited suppliers (+ direct dealer API)',
        'Unlimited feeds and output channels',
        'Hourly sync (1h) or via Webhooks',
        '10,000 AI Credits/month + priority processing',
        '50 GB Cloud storage + Custom S3 (BYOS)',
        '10+ team seats (expandable)',
        'B2B dealer price lists & custom mappings',
        'Full audit trail log',
        'White-label PDF reports',
        'REST API + Webhooks',
        'Dedicated account manager (within 2h)',
        'SLA 99.9% Uptime guarantee',
      ],
    },
    create: {
      code: 'ENTERPRISE',
      nameUk: 'Корпоративний',
      nameEn: 'Enterprise',
      descriptionUk: 'Безлімітна потужність, B2B дилерські прайси та прямий API.',
      descriptionEn: 'Unlimited power, B2B dealer price lists and direct API.',
      priceMonthly: 3990,
      priceYearly: 38280,
      currency: 'UAH',
      maxXmlLimit: 500000,
      aiCredits: 10000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 50,
      maxTeamSeats: 10,
      maxSuppliersLimit: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        '500,000+ SKU (Безліміт товарів)',
        'Необмежена кількість постачальників (+ прямі API дилерів)',
        'Необмежені фіди та канали експорту',
        'Синхронізація щогодини (1 год) або по Webhook',
        '10,000 AI Кредитів/міс + пріоритетна обробка',
        '50 GB сховища + можливість власного S3 (BYOS)',
        '10+ місць для команди (з можливістю розширення)',
        'B2B дилерські прайси та кастомні мапінги',
        'Журнал аудиту дій (Audit Log)',
        'White-label PDF звіти',
        'REST API + Webhooks',
        'Персональний акаунт-менеджер (до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        '500,000+ SKU (Unlimited products)',
        'Unlimited suppliers (+ direct dealer API)',
        'Unlimited feeds and output channels',
        'Hourly sync (1h) or via Webhooks',
        '10,000 AI Credits/month + priority processing',
        '50 GB Cloud storage + Custom S3 (BYOS)',
        '10+ team seats (expandable)',
        'B2B dealer price lists & custom mappings',
        'Full audit trail log',
        'White-label PDF reports',
        'REST API + Webhooks',
        'Dedicated account manager (within 2h)',
        'SLA 99.9% Uptime guarantee',
      ],
    },
  });

  // ============================================================
  // 2. Create Single Super Admin (Owner — No customer licenses needed)
  // ============================================================
  const superAdmin = await prisma.user.upsert({
    where: { email: 'admin@admin.com' },
    update: {
      passwordHash: ownerPasswordHash,
      role: Role.SUPER_ADMIN,
      fullName: 'Super Administrator',
    },
    create: {
      email: 'admin@admin.com',
      passwordHash: ownerPasswordHash,
      fullName: 'Super Administrator',
      role: Role.SUPER_ADMIN,
    },
  });

  // Remove any legacy mock admins or dummy licenses
  await prisma.license.deleteMany({
    where: {
      user: { email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] } },
    },
  });
  await prisma.organizationMember.deleteMany({
    where: {
      user: { email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] } },
    },
  });
  await prisma.organization.deleteMany({
    where: {
      id: {
        in: [
          '00000000-0000-0000-0000-000000000000',
          '00000000-0000-0000-0000-000000000001',
          '00000000-0000-0000-0000-000000000002',
        ],
      },
    },
  });
  await prisma.user.deleteMany({
    where: {
      email: { in: ['admin@gmail.com', 'admin@smartfeed.studio'] },
    },
  });
  // Super Admin is platform host, delete any customer licenses
  await prisma.license.deleteMany({
    where: { userId: superAdmin.id },
  });

  // ============================================================
  // 5. Seed Dynamic Navigation Items for Desktop & Admin
  // ============================================================
  const navigationItems = [
    {
      key: 'dashboard',
      labelUk: 'Дашборд',
      labelEn: 'Dashboard',
      path: '/',
      icon: 'LayoutDashboard',
      order: 1,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'catalogs',
      labelUk: 'Каталоги товарів',
      labelEn: 'Product Catalogs',
      path: '/catalogs',
      icon: 'Layers',
      order: 2,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'ai_enrichment',
      labelUk: 'AI Збагачення',
      labelEn: 'AI Enrichment',
      path: '/ai-enrichment',
      icon: 'Sparkles',
      order: 3,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'cloud_sync',
      labelUk: 'Хмарна синхронізація',
      labelEn: 'Cloud Sync',
      path: '/cloud-sync',
      icon: 'Cloud',
      order: 4,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'plans',
      labelUk: 'Тарифи',
      labelEn: 'Plans & Pricing',
      path: '/plans',
      icon: 'CreditCard',
      order: 5,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'team',
      labelUk: 'Команда',
      labelEn: 'Team',
      path: '/team',
      icon: 'Users',
      order: 6,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'settings',
      labelUk: 'Налаштування',
      labelEn: 'Settings',
      path: '/settings',
      icon: 'Settings',
      order: 7,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    // ============================================================
    // Admin Portal Navigation Items
    // ============================================================
    {
      key: 'admin_dashboard',
      labelUk: 'Дашборд',
      labelEn: 'Dashboard',
      path: '/',
      icon: 'LayoutDashboard',
      order: 1,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_users',
      labelUk: 'Користувачі',
      labelEn: 'Users',
      path: '/users',
      icon: 'Users',
      order: 2,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_plans',
      labelUk: 'Тарифи',
      labelEn: 'Tariff Plans',
      path: '/plans',
      icon: 'Layers',
      order: 3,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_licenses',
      labelUk: 'Ліцензії',
      labelEn: 'Licenses',
      path: '/licenses',
      icon: 'KeyRound',
      order: 4,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_transactions',
      labelUk: 'Транзакції',
      labelEn: 'Transactions',
      path: '/transactions',
      icon: 'Receipt',
      order: 5,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_payment_settings',
      labelUk: 'Платіжні системи',
      labelEn: 'Payment Gateways',
      path: '/settings/payments',
      icon: 'CreditCard',
      order: 6,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
    {
      key: 'admin_navigation',
      labelUk: 'Навігація меню',
      labelEn: 'Navigation Menu',
      path: '/navigation',
      icon: 'Compass',
      order: 7,
      isVisible: true,
      requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.ADMIN_PORTAL,
    },
  ];

  for (const item of navigationItems) {
    await prisma.navigationItem.upsert({
      where: { key: item.key },
      update: {
        labelUk: item.labelUk,
        labelEn: item.labelEn,
        path: item.path,
        icon: item.icon,
        order: item.order,
        isVisible: item.isVisible,
        requiredRoles: item.requiredRoles,
        requiredPlan: item.requiredPlan,
        targetApp: item.targetApp,
      },
      create: item,
    });
  }

  // ============================================================
  // 6. Seed Default Payment Gateway Settings (WayForPay Sandbox)
  // ============================================================
  await prisma.paymentSetting.upsert({
    where: { provider: PaymentProvider.WAYFORPAY },
    update: {
      isEnabled: true,
      isTestMode: true,
      merchantAccount: 'test_merch_n1',
      merchantSecretKey: 'flk3409refn54t54t*FNJRET',
      merchantDomain: 'www.market.ua',
      serviceUrl: 'http://localhost:4000/api/payments/wayforpay/webhook',
      returnUrl: 'http://localhost:1420/payment/result',
    },
    create: {
      provider: PaymentProvider.WAYFORPAY,
      isEnabled: true,
      isTestMode: true,
      merchantAccount: 'test_merch_n1',
      merchantSecretKey: 'flk3409refn54t54t*FNJRET',
      merchantDomain: 'www.market.ua',
      serviceUrl: 'http://localhost:4000/api/payments/wayforpay/webhook',
      returnUrl: 'http://localhost:1420/payment/result',
    },
  });

  console.log('✅ Seeding completed:');
  console.log(
    `   - Seeded 4 tariff plans: STARTER ($0), GROWTH ($29), PRO ($79), ENTERPRISE ($249)`,
  );
  console.log(`   - Super Admin: admin@admin.com       (Role: SUPER_ADMIN)`);
  console.log(`   - Seeded ${navigationItems.length} dynamic navigation items`);
  console.log(`   - Seeded default WayForPay Sandbox payment gateway settings`);
  void starterPlan;
  void growthPlan;
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
