import { PrismaClient, Role, PlanType, TargetApp } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding for SmartFeed Studio...');

  const saltRounds = 10;
  const adminPasswordHash = await bcrypt.hash('AdminPassword123!', saltRounds);
  const gmailAdminPasswordHash = await bcrypt.hash('admin@gmail.com', saltRounds);
  const userPasswordHash = await bcrypt.hash('UserPassword123!', saltRounds);

  // ============================================================
  // 1. Seed Dynamic Tariff Plans (STARTER, GROWTH, PRO, ENTERPRISE)
  // ============================================================

  const starterPlan = await prisma.tariffPlan.upsert({
    where: { code: 'STARTER' },
    update: {
      nameUk: 'Старт',
      nameEn: 'Starter',
      descriptionUk: 'Спробуй безкоштовно, без кредитної картки. Відчуй потужність платформи.',
      descriptionEn: 'Try for free, no credit card required. Feel the platform power.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'USD',
      // Quotas
      maxXmlLimit: 500,
      aiCredits: 0,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      // Feature flags
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      // Display
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 500 SKU товарів',
        '1 активний XML/CSV фід',
        '1 канал виводу (Rozetka або файл)',
        'Ручне оновлення фіду',
        'Зашифрована локальна SQLite база',
        'Документація та FAQ',
      ],
      featuresEn: [
        'Up to 500 product SKUs',
        '1 active XML/CSV feed',
        '1 output channel (Rozetka or file)',
        'Manual feed updates only',
        'Encrypted local SQLite storage',
        'Documentation & FAQ',
      ],
    },
    create: {
      code: 'STARTER',
      nameUk: 'Старт',
      nameEn: 'Starter',
      descriptionUk: 'Спробуй безкоштовно, без кредитної картки. Відчуй потужність платформи.',
      descriptionEn: 'Try for free, no credit card required. Feel the platform power.',
      priceMonthly: 0,
      priceYearly: 0,
      currency: 'USD',
      maxXmlLimit: 500,
      aiCredits: 0,
      canCloudBackup: false,
      maxFeedsLimit: 1,
      maxChannelsLimit: 1,
      syncFrequencyHours: 0,
      maxStorageGb: 0,
      maxTeamSeats: 1,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 1,
      durationDays: 7,
      featuresUk: [
        'До 500 SKU товарів',
        '1 активний XML/CSV фід',
        '1 канал виводу (Rozetka або файл)',
        'Ручне оновлення фіду',
        'Зашифрована локальна SQLite база',
        'Документація та FAQ',
      ],
      featuresEn: [
        'Up to 500 product SKUs',
        '1 active XML/CSV feed',
        '1 output channel (Rozetka or file)',
        'Manual feed updates only',
        'Encrypted local SQLite storage',
        'Documentation & FAQ',
      ],
    },
  });

  const growthPlan = await prisma.tariffPlan.upsert({
    where: { code: 'GROWTH' },
    update: {
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та зосередься на продажах. Для активних продавців.',
      descriptionEn: 'Automate your feeds and focus on sales. For active solo sellers.',
      priceMonthly: 29,
      priceYearly: 290,
      currency: 'USD',
      maxXmlLimit: 10000,
      aiCredits: 50,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 1,
      maxTeamSeats: 1,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 10,000 SKU товарів',
        '5 активних фідів',
        '3 канали виводу (Rozetka, Prom.ua, Google Shopping)',
        'Авто-оновлення 1 раз на добу',
        '50 AI Кредитів на місяць',
        'Хмарний бекап 1 GB (ручний snapshot)',
        'Базова трансформація даних',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 10,000 product SKUs',
        '5 active feeds',
        '3 output channels (Rozetka, Prom.ua, Google Shopping)',
        'Auto-sync once per day',
        '50 AI Credits per month',
        '1 GB Cloud backup (manual snapshot)',
        'Basic data transformation rules',
        'Email support within 48h',
      ],
    },
    create: {
      code: 'GROWTH',
      nameUk: 'Зріст',
      nameEn: 'Growth',
      descriptionUk: 'Автоматизуй фіди та зосередься на продажах. Для активних продавців.',
      descriptionEn: 'Automate your feeds and focus on sales. For active solo sellers.',
      priceMonthly: 29,
      priceYearly: 290,
      currency: 'USD',
      maxXmlLimit: 10000,
      aiCredits: 50,
      canCloudBackup: true,
      maxFeedsLimit: 5,
      maxChannelsLimit: 3,
      syncFrequencyHours: 24,
      maxStorageGb: 1,
      maxTeamSeats: 1,
      hasApiAccess: false,
      hasWebhooks: false,
      hasFeedDiff: false,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: false,
      isActive: true,
      order: 2,
      durationDays: 30,
      featuresUk: [
        'До 10,000 SKU товарів',
        '5 активних фідів',
        '3 канали виводу (Rozetka, Prom.ua, Google Shopping)',
        'Авто-оновлення 1 раз на добу',
        '50 AI Кредитів на місяць',
        'Хмарний бекап 1 GB (ручний snapshot)',
        'Базова трансформація даних',
        'Email підтримка до 48 год',
      ],
      featuresEn: [
        'Up to 10,000 product SKUs',
        '5 active feeds',
        '3 output channels (Rozetka, Prom.ua, Google Shopping)',
        'Auto-sync once per day',
        '50 AI Credits per month',
        '1 GB Cloud backup (manual snapshot)',
        'Basic data transformation rules',
        'Email support within 48h',
      ],
    },
  });

  const proPlan = await prisma.tariffPlan.upsert({
    where: { code: 'PRO' },
    update: {
      nameUk: 'Про',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація фідів з AI — для команд, що масштабуються.',
      descriptionEn: 'Full feed automation with AI — for scaling teams and agencies.',
      priceMonthly: 79,
      priceYearly: 790,
      currency: 'USD',
      maxXmlLimit: 100000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'Необмежена кількість фідів',
        '15 каналів виводу (Hotline, Prom.ua, Facebook Catalog і ін.)',
        'Авто-оновлення кожні 4 години',
        '500 AI Кредитів/місяць',
        'Хмарний бекап 10 GB (авто-snapshot щодня)',
        'Розширені правила трансформації',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        '3 місця для команди',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Unlimited feeds',
        '15 output channels (Hotline, Prom.ua, Facebook Catalog, etc.)',
        'Auto-sync every 4 hours',
        '500 AI Credits per month',
        '10 GB Cloud backup (daily auto-snapshot)',
        'Advanced transformation rules',
        'Feed version diff comparison',
        'REST API access',
        '3 team seats',
        'Live Chat support within 8h',
      ],
    },
    create: {
      code: 'PRO',
      nameUk: 'Про',
      nameEn: 'Pro',
      descriptionUk: 'Повна автоматизація фідів з AI — для команд, що масштабуються.',
      descriptionEn: 'Full feed automation with AI — for scaling teams and agencies.',
      priceMonthly: 79,
      priceYearly: 790,
      currency: 'USD',
      maxXmlLimit: 100000,
      aiCredits: 500,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      syncFrequencyHours: 4,
      maxStorageGb: 10,
      maxTeamSeats: 3,
      hasApiAccess: true,
      hasWebhooks: false,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      hasCustomS3: false,
      hasPriorityAi: false,
      slaUptimePercent: null,
      isPopular: true,
      isActive: true,
      order: 3,
      durationDays: 30,
      featuresUk: [
        'До 100,000 SKU товарів',
        'Необмежена кількість фідів',
        '15 каналів виводу (Hotline, Prom.ua, Facebook Catalog і ін.)',
        'Авто-оновлення кожні 4 години',
        '500 AI Кредитів/місяць',
        'Хмарний бекап 10 GB (авто-snapshot щодня)',
        'Розширені правила трансформації',
        'Порівняння версій фіду (Diff)',
        'REST API доступ',
        '3 місця для команди',
        'Live Chat підтримка до 8 год',
      ],
      featuresEn: [
        'Up to 100,000 product SKUs',
        'Unlimited feeds',
        '15 output channels (Hotline, Prom.ua, Facebook Catalog, etc.)',
        'Auto-sync every 4 hours',
        '500 AI Credits per month',
        '10 GB Cloud backup (daily auto-snapshot)',
        'Advanced transformation rules',
        'Feed version diff comparison',
        'REST API access',
        '3 team seats',
        'Live Chat support within 8h',
      ],
    },
  });

  const enterprisePlan = await prisma.tariffPlan.upsert({
    where: { code: 'ENTERPRISE' },
    update: {
      nameUk: 'Корпоратив',
      nameEn: 'Enterprise',
      descriptionUk: 'Корпоративна потужність без enterprise-ціни конкурентів. Для великих мереж.',
      descriptionEn:
        'Enterprise power without competitor enterprise pricing. For large retail networks.',
      priceMonthly: 249,
      priceYearly: 2490,
      currency: 'USD',
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 999999,
      maxTeamSeats: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        'Необмежена кількість SKU товарів',
        'Необмежені фіди та канали виводу',
        'Реальний час оновлення (кожну годину)',
        '5,000 AI Кредитів/місяць + пріоритетна черга',
        'Необмежений хмарний бекап',
        'Власний S3/MinIO ендпоінт клієнта',
        'Необмежені місця для команди',
        'SSO / SAML (Google Workspace, Okta)',
        'Журнал аудиту всіх дій',
        'White-label PDF звіти для клієнтів',
        'REST API + Webhook',
        'Пріоритетна підтримка (Telegram, до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        'Unlimited product SKUs',
        'Unlimited feeds and output channels',
        'Near-realtime sync (every hour)',
        '5,000 AI Credits/month + priority queue',
        'Unlimited cloud backup storage',
        'Custom S3/MinIO endpoint',
        'Unlimited team seats',
        'SSO / SAML (Google Workspace, Okta)',
        'Full audit log of all actions',
        'White-label PDF reports for clients',
        'REST API + Webhook push',
        'Priority support (Telegram, within 2h)',
        'SLA 99.9% uptime guarantee',
      ],
    },
    create: {
      code: 'ENTERPRISE',
      nameUk: 'Корпоратив',
      nameEn: 'Enterprise',
      descriptionUk: 'Корпоративна потужність без enterprise-ціни конкурентів. Для великих мереж.',
      descriptionEn:
        'Enterprise power without competitor enterprise pricing. For large retail networks.',
      priceMonthly: 249,
      priceYearly: 2490,
      currency: 'USD',
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      canCloudBackup: true,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      syncFrequencyHours: 1,
      maxStorageGb: 999999,
      maxTeamSeats: 999999,
      hasApiAccess: true,
      hasWebhooks: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      hasCustomS3: true,
      hasPriorityAi: true,
      slaUptimePercent: 99.9,
      isPopular: false,
      isActive: true,
      order: 4,
      durationDays: 365,
      featuresUk: [
        'Необмежена кількість SKU товарів',
        'Необмежені фіди та канали виводу',
        'Реальний час оновлення (кожну годину)',
        '5,000 AI Кредитів/місяць + пріоритетна черга',
        'Необмежений хмарний бекап',
        'Власний S3/MinIO ендпоінт клієнта',
        'Необмежені місця для команди',
        'SSO / SAML (Google Workspace, Okta)',
        'Журнал аудиту всіх дій',
        'White-label PDF звіти для клієнтів',
        'REST API + Webhook',
        'Пріоритетна підтримка (Telegram, до 2 год)',
        'SLA 99.9% Uptime гарантія',
      ],
      featuresEn: [
        'Unlimited product SKUs',
        'Unlimited feeds and output channels',
        'Near-realtime sync (every hour)',
        '5,000 AI Credits/month + priority queue',
        'Unlimited cloud backup storage',
        'Custom S3/MinIO endpoint',
        'Unlimited team seats',
        'SSO / SAML (Google Workspace, Okta)',
        'Full audit log of all actions',
        'White-label PDF reports for clients',
        'REST API + Webhook push',
        'Priority support (Telegram, within 2h)',
        'SLA 99.9% uptime guarantee',
      ],
    },
  });

  // ============================================================
  // 2. Create Super Admin (admin@smartfeed.studio)
  // ============================================================
  const admin = await prisma.user.upsert({
    where: { email: 'admin@smartfeed.studio' },
    update: { passwordHash: adminPasswordHash },
    create: {
      email: 'admin@smartfeed.studio',
      passwordHash: adminPasswordHash,
      fullName: 'Super Administrator',
      role: Role.SUPER_ADMIN,
    },
  });

  await prisma.license.upsert({
    where: { licenseKey: 'SF-ENTERPRISE-ADMIN-0001' },
    update: { tariffPlanId: enterprisePlan.id },
    create: {
      userId: admin.id,
      tariffPlanId: enterprisePlan.id,
      licenseKey: 'SF-ENTERPRISE-ADMIN-0001',
      planType: PlanType.ENTERPRISE,
      canCloudBackup: true,
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      maxTeamSeats: 999999,
      hasApiAccess: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      isActive: true,
      expiresAt: null,
    },
  });

  // ============================================================
  // 3. Create Super Admin (admin@gmail.com)
  // ============================================================
  const gmailAdmin = await prisma.user.upsert({
    where: { email: 'admin@gmail.com' },
    update: { passwordHash: gmailAdminPasswordHash, role: Role.SUPER_ADMIN },
    create: {
      email: 'admin@gmail.com',
      passwordHash: gmailAdminPasswordHash,
      fullName: 'Admin User',
      role: Role.SUPER_ADMIN,
    },
  });

  await prisma.license.upsert({
    where: { licenseKey: 'SF-ENTERPRISE-GMAIL-ADMIN' },
    update: { tariffPlanId: enterprisePlan.id },
    create: {
      userId: gmailAdmin.id,
      tariffPlanId: enterprisePlan.id,
      licenseKey: 'SF-ENTERPRISE-GMAIL-ADMIN',
      planType: PlanType.ENTERPRISE,
      canCloudBackup: true,
      maxXmlLimit: 999999999,
      aiCredits: 5000,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 999999,
      maxTeamSeats: 999999,
      hasApiAccess: true,
      hasFeedDiff: true,
      hasWhiteLabel: true,
      hasSso: true,
      hasAuditLog: true,
      isActive: true,
      expiresAt: null,
    },
  });

  // ============================================================
  // 4. Create Demo User (PRO plan)
  // ============================================================
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@smartfeed.studio' },
    update: { passwordHash: userPasswordHash },
    create: {
      email: 'demo@smartfeed.studio',
      passwordHash: userPasswordHash,
      fullName: 'Demo Store Manager',
      role: Role.USER,
    },
  });

  await prisma.license.upsert({
    where: { licenseKey: 'SF-PRO-DEMO-9900-1122' },
    update: { tariffPlanId: proPlan.id },
    create: {
      userId: demoUser.id,
      tariffPlanId: proPlan.id,
      licenseKey: 'SF-PRO-DEMO-9900-1122',
      planType: PlanType.PRO,
      canCloudBackup: true,
      maxXmlLimit: 100000,
      aiCredits: 500,
      maxFeedsLimit: 999999,
      maxChannelsLimit: 15,
      maxTeamSeats: 3,
      hasApiAccess: true,
      hasFeedDiff: true,
      hasWhiteLabel: false,
      hasSso: false,
      hasAuditLog: false,
      isActive: true,
    },
  });

  // ============================================================
  // 5. Seed Dynamic Navigation Items for Desktop & Admin
  // ============================================================
  const navigationItems = [
    {
      key: 'dashboard',
      labelUk: 'Дашборд',
      labelEn: 'Dashboard',
      path: '/',
      icon: 'LayoutDashboard',
      order: 1,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'catalogs',
      labelUk: 'Каталоги товарів',
      labelEn: 'Product Catalogs',
      path: '/catalogs',
      icon: 'Layers',
      order: 2,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'ai_enrichment',
      labelUk: 'AI Збагачення',
      labelEn: 'AI Enrichment',
      path: '/ai-enrichment',
      icon: 'Sparkles',
      order: 3,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'cloud_sync',
      labelUk: 'Хмарна синхронізація',
      labelEn: 'Cloud Sync',
      path: '/cloud-sync',
      icon: 'Cloud',
      order: 4,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: PlanType.GROWTH,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'plans',
      labelUk: 'Тарифи',
      labelEn: 'Plans & Pricing',
      path: '/plans',
      icon: 'CreditCard',
      order: 5,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
    {
      key: 'settings',
      labelUk: 'Налаштування',
      labelEn: 'Settings',
      path: '/settings',
      icon: 'Settings',
      order: 6,
      isVisible: true,
      requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
      requiredPlan: null,
      targetApp: TargetApp.DESKTOP,
    },
  ];

  for (const item of navigationItems) {
    await prisma.navigationItem.upsert({
      where: { key: item.key },
      update: {
        labelUk: item.labelUk,
        labelEn: item.labelEn,
        path: item.path,
        icon: item.icon,
        order: item.order,
        isVisible: item.isVisible,
        requiredRoles: item.requiredRoles,
        requiredPlan: item.requiredPlan,
        targetApp: item.targetApp,
      },
      create: item,
    });
  }

  console.log('✅ Seeding completed:');
  console.log(
    `   - Seeded 4 tariff plans: STARTER ($0), GROWTH ($29), PRO ($79), ENTERPRISE ($249)`,
  );
  console.log(`   - Super Admin: admin@gmail.com       (Password: admin@gmail.com)`);
  console.log(`   - Super Admin: admin@smartfeed.studio (Password: AdminPassword123!)`);
  console.log(`   - Demo User:   demo@smartfeed.studio  (Password: UserPassword123!)`);
  console.log(`   - Seeded ${navigationItems.length} dynamic navigation items`);
  void starterPlan;
  void growthPlan;
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
