import { PlanType } from '../enums/index.js';
import { PlanLimits } from '../dtos/license.dto.js';

export const PLAN_LIMITS_MAP: Record<PlanType, PlanLimits> = {
  [PlanType.STARTER]: {
    planType: PlanType.STARTER,
    maxXmlLimit: 500,
    aiCredits: 0,
    canCloudBackup: false,
    maxFeedsLimit: 1,
    maxChannelsLimit: 1,
    maxTeamSeats: 1,
    hasApiAccess: false,
    hasFeedDiff: false,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
  },
  [PlanType.GROWTH]: {
    planType: PlanType.GROWTH,
    maxXmlLimit: 10000,
    aiCredits: 50,
    canCloudBackup: true,
    maxFeedsLimit: 5,
    maxChannelsLimit: 3,
    maxTeamSeats: 1,
    hasApiAccess: false,
    hasFeedDiff: false,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
  },
  [PlanType.PRO]: {
    planType: PlanType.PRO,
    maxXmlLimit: 100000,
    aiCredits: 500,
    canCloudBackup: true,
    maxFeedsLimit: 999999,
    maxChannelsLimit: 15,
    maxTeamSeats: 3,
    hasApiAccess: true,
    hasFeedDiff: true,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
  },
  [PlanType.ENTERPRISE]: {
    planType: PlanType.ENTERPRISE,
    maxXmlLimit: 999999999,
    aiCredits: 5000,
    canCloudBackup: true,
    maxFeedsLimit: 999999,
    maxChannelsLimit: 999999,
    maxTeamSeats: 999999,
    hasApiAccess: true,
    hasFeedDiff: true,
    hasWhiteLabel: true,
    hasSso: true,
    hasAuditLog: true,
  },
};

export const S3_FOLDERS = {
  SNAPSHOTS: 'snapshots',
  IMAGES: 'images',
  FEEDS: 'feeds',
} as const;
