import { PrismaClient, Role, PlanType, TargetApp } from '@/generated/prisma/client';

export const navigationItemsSeedData = [
  // ============================================================
  // Desktop Navigation Items
  // ============================================================
  {
    key: 'dashboard',
    labelUk: 'Дашборд',
    labelEn: 'Dashboard',
    path: '/',
    icon: 'LayoutDashboard',
    order: 1,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'catalogs',
    labelUk: 'Каталоги товарів',
    labelEn: 'Product Catalogs',
    path: '/catalogs',
    icon: 'Layers',
    order: 2,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'suppliers',
    labelUk: 'Постачальники',
    labelEn: 'Suppliers',
    path: '/suppliers',
    icon: 'Building2',
    order: 3,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'ai_enrichment',
    labelUk: 'AI Асистент',
    labelEn: 'AI Assistant',
    path: '/ai-enrichment',
    icon: 'Sparkles',
    order: 4,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: PlanType.GROWTH,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'cloud_sync',
    labelUk: 'Хмарна синхронізація',
    labelEn: 'Cloud Sync',
    path: '/cloud-sync',
    icon: 'Cloud',
    order: 5,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: PlanType.GROWTH,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'plans',
    labelUk: 'Тарифи',
    labelEn: 'Plans & Pricing',
    path: '/plans',
    icon: 'CreditCard',
    order: 6,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'team',
    labelUk: 'Команда',
    labelEn: 'Team',
    path: '/team',
    icon: 'Users',
    order: 7,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  {
    key: 'settings',
    labelUk: 'Налаштування',
    labelEn: 'Settings',
    path: '/settings',
    icon: 'Settings',
    order: 8,
    isVisible: true,
    requiredRoles: [Role.USER, Role.ADMIN, Role.SUPER_ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.DESKTOP,
  },
  // ============================================================
  // Admin Portal Navigation Items
  // ============================================================
  {
    key: 'admin_dashboard',
    labelUk: 'Дашборд',
    labelEn: 'Dashboard',
    path: '/',
    icon: 'LayoutDashboard',
    order: 1,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_users',
    labelUk: 'Користувачі',
    labelEn: 'Users',
    path: '/users',
    icon: 'Users',
    order: 2,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_plans',
    labelUk: 'Тарифи',
    labelEn: 'Tariff Plans',
    path: '/plans',
    icon: 'Layers',
    order: 3,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_licenses',
    labelUk: 'Ліцензії',
    labelEn: 'Licenses',
    path: '/licenses',
    icon: 'KeyRound',
    order: 4,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_transactions',
    labelUk: 'Транзакції',
    labelEn: 'Transactions',
    path: '/transactions',
    icon: 'Receipt',
    order: 5,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_payment_settings',
    labelUk: 'Платіжні системи',
    labelEn: 'Payment Gateways',
    path: '/settings/payments',
    icon: 'CreditCard',
    order: 6,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
  {
    key: 'admin_navigation',
    labelUk: 'Навігація меню',
    labelEn: 'Navigation Menu',
    path: '/navigation',
    icon: 'Compass',
    order: 7,
    isVisible: true,
    requiredRoles: [Role.SUPER_ADMIN, Role.ADMIN],
    requiredPlan: null,
    targetApp: TargetApp.ADMIN_PORTAL,
  },
];

export async function seedNavigation(prisma: PrismaClient): Promise<void> {
  for (const item of navigationItemsSeedData) {
    await prisma.navigationItem.upsert({
      where: { key: item.key },
      update: {
        labelUk: item.labelUk,
        labelEn: item.labelEn,
        path: item.path,
        icon: item.icon,
        order: item.order,
        isVisible: item.isVisible,
        requiredRoles: item.requiredRoles,
        requiredPlan: item.requiredPlan,
        targetApp: item.targetApp,
      },
      create: item,
    });
  }
}
