import { PrismaClient } from '@/generated/prisma/client';

export const tariffPlansSeedData = [
  {
    code: 'STARTER',
    nameUk: 'Старт',
    nameEn: 'Starter',
    descriptionUk:
      '7 днів безкоштовно при реєстрації. Ідеально для швидкого старту та 1 маркетплейсу.',
    descriptionEn: '7-day free trial on signup. Perfect for a quick start on 1 marketplace.',
    priceMonthly: 299,
    priceYearly: 2999,
    currency: 'UAH',
    maxXmlLimit: 1000,
    aiCredits: 50,
    canCloudBackup: false,
    maxFeedsLimit: 1,
    maxChannelsLimit: 1,
    syncFrequencyHours: 0,
    maxStorageGb: 0,
    maxTeamSeats: 1,
    maxSuppliersLimit: 1,
    hasApiAccess: false,
    hasWebhooks: false,
    hasFeedDiff: false,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
    hasCustomS3: false,
    hasPriorityAi: false,
    slaUptimePercent: null,
    isPopular: false,
    isActive: true,
    order: 1,
    durationDays: 30,
    featuresUk: [
      '7 днів безкоштовного пробного періоду при реєстрації',
      'До 1,000 SKU товарів',
      '1 постачальник (базовий прайс)',
      '1 активний фід',
      '1 будь-який канал експорту на вибір (Rozetka, Prom, Google чи кастомний)',
      '50 AI Кредитів на тест',
      'Зашифрована локальна SQLite база',
      'Ручне оновлення',
    ],
    featuresEn: [
      '7-day free trial upon registration',
      'Up to 1,000 product SKUs',
      '1 product supplier (single price)',
      '1 active feed',
      '1 export channel of choice (Rozetka, Prom, Google or custom)',
      '50 trial AI Credits',
      'Encrypted local SQLite storage',
      'Manual sync',
    ],
  },
  {
    code: 'GROWTH',
    nameUk: 'Зріст',
    nameEn: 'Growth',
    descriptionUk: 'Автоматизуй фіди та продавай на декількох маркетплейсах одночасно.',
    descriptionEn: 'Automate feeds and sell on multiple marketplaces simultaneously.',
    priceMonthly: 690,
    priceYearly: 6600,
    currency: 'UAH',
    maxXmlLimit: 20000,
    aiCredits: 500,
    canCloudBackup: true,
    maxFeedsLimit: 5,
    maxChannelsLimit: 3,
    syncFrequencyHours: 24,
    maxStorageGb: 2,
    maxTeamSeats: 1,
    maxSuppliersLimit: 3,
    hasApiAccess: false,
    hasWebhooks: false,
    hasFeedDiff: false,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
    hasCustomS3: false,
    hasPriorityAi: false,
    slaUptimePercent: null,
    isPopular: false,
    isActive: true,
    order: 2,
    durationDays: 30,
    featuresUk: [
      'До 20,000 SKU товарів',
      'До 3 постачальників (порівняння цін та наявності)',
      '5 активних фідів',
      'До 3 каналів експорту одночасно (Rozetka + Prom + Google)',
      'Авто-оновлення 1 раз на добу (24 год)',
      '500 AI Кредитів на місяць',
      'Хмарний бекап 2 GB (до 5 знімків)',
      'Індивідуальні націнки за постачальниками',
      'Email підтримка до 48 год',
    ],
    featuresEn: [
      'Up to 20,000 product SKUs',
      'Up to 3 suppliers (price comparison)',
      '5 active feeds',
      'Up to 3 output channels (Rozetka + Prom + Google)',
      'Auto-sync once per day (24h)',
      '500 AI Credits per month',
      '2 GB Cloud backup (up to 5 snapshots)',
      'Per-supplier markup rules',
      'Email support within 48h',
    ],
  },
  {
    code: 'PRO',
    nameUk: 'Професійний',
    nameEn: 'Pro',
    descriptionUk: 'Повна автоматизація, мульти-склад та командна робота.',
    descriptionEn: 'Full automation, multi-supplier warehouse & team collaboration.',
    priceMonthly: 1490,
    priceYearly: 14280,
    currency: 'UAH',
    maxXmlLimit: 100000,
    aiCredits: 2500,
    canCloudBackup: true,
    maxFeedsLimit: 999999,
    maxChannelsLimit: 15,
    syncFrequencyHours: 4,
    maxStorageGb: 10,
    maxTeamSeats: 3,
    maxSuppliersLimit: 15,
    hasApiAccess: true,
    hasWebhooks: false,
    hasFeedDiff: true,
    hasWhiteLabel: false,
    hasSso: false,
    hasAuditLog: false,
    hasCustomS3: false,
    hasPriorityAi: false,
    slaUptimePercent: null,
    isPopular: true,
    isActive: true,
    order: 3,
    durationDays: 30,
    featuresUk: [
      'До 100,000 SKU товарів',
      'До 15 постачальників (авто-зіставлення за EAN/артикулом)',
      'Необмежена кількість фідів',
      'До 15 каналів експорту (+ Kasta, Epicentr, Allo)',
      'Авто-оновлення кожні 4 години',
      '2,500 AI Кредитів на місяць',
      'Хмарний бекап 10 GB + Hub & Spoke синхронізація команди',
      '3 місця для команди (Власник + 2 менеджери)',
      'Порівняння версій фіду (Diff)',
      'REST API доступ',
      'Договір та акти для юросіб',
      'Live Chat підтримка до 8 год',
    ],
    featuresEn: [
      'Up to 100,000 product SKUs',
      'Up to 15 suppliers (auto-matching by EAN/SKU)',
      'Unlimited feeds',
      'Up to 15 output channels (+ Kasta, Epicentr, Allo)',
      'Auto-sync every 4 hours',
      '2,500 AI Credits per month',
      '10 GB Cloud backup + Team Hub & Spoke sync',
      '3 team seats (Owner + 2 members)',
      'Feed version diff comparison',
      'REST API access',
      'Invoices & B2B contracts',
      'Live Chat support within 8h',
    ],
  },
  {
    code: 'ENTERPRISE',
    nameUk: 'Корпоративний',
    nameEn: 'Enterprise',
    descriptionUk: 'Безлімітна потужність, B2B дилерські прайси та прямий API.',
    descriptionEn: 'Unlimited power, B2B dealer price lists and direct API.',
    priceMonthly: 3990,
    priceYearly: 38280,
    currency: 'UAH',
    maxXmlLimit: 500000,
    aiCredits: 10000,
    canCloudBackup: true,
    maxFeedsLimit: 999999,
    maxChannelsLimit: 999999,
    syncFrequencyHours: 1,
    maxStorageGb: 50,
    maxTeamSeats: 10,
    maxSuppliersLimit: 999999,
    hasApiAccess: true,
    hasWebhooks: true,
    hasFeedDiff: true,
    hasWhiteLabel: true,
    hasSso: true,
    hasAuditLog: true,
    hasCustomS3: true,
    hasPriorityAi: true,
    slaUptimePercent: 99.9,
    isPopular: false,
    isActive: true,
    order: 4,
    durationDays: 365,
    featuresUk: [
      '500,000+ SKU (Безліміт товарів)',
      'Необмежена кількість постачальників (+ прямі API дилерів)',
      'Необмежені фіди та канали експорту',
      'Синхронізація щогодини (1 год) або по Webhook',
      '10,000 AI Кредитів/міс + пріоритетна обробка',
      '50 GB сховища + можливість власного S3 (BYOS)',
      '10+ місць для команди (з можливістю розширення)',
      'B2B дилерські прайси та кастомні мапінги',
      'Журнал аудиту дій (Audit Log)',
      'White-label PDF звіти',
      'REST API + Webhooks',
      'Персональний акаунт-менеджер (до 2 год)',
      'SLA 99.9% Uptime гарантія',
    ],
    featuresEn: [
      '500,000+ SKU (Unlimited products)',
      'Unlimited suppliers (+ direct dealer API)',
      'Unlimited feeds and output channels',
      'Hourly sync (1h) or via Webhooks',
      '10,000 AI Credits/month + priority processing',
      '50 GB Cloud storage + Custom S3 (BYOS)',
      '10+ team seats (expandable)',
      'B2B dealer price lists & custom mappings',
      'Full audit trail log',
      'White-label PDF reports',
      'REST API + Webhooks',
      'Dedicated account manager (within 2h)',
      'SLA 99.9% Uptime guarantee',
    ],
  },
];

export async function seedTariffPlans(prisma: PrismaClient): Promise<void> {
  for (const plan of tariffPlansSeedData) {
    await prisma.tariffPlan.upsert({
      where: { code: plan.code },
      update: plan,
      create: plan,
    });
  }
}
