import { TariffPlanDto } from '@smartfeed/shared';

export function mapTariffPlanToDto(plan: any): TariffPlanDto {
  return {
    id: plan.id,
    code: plan.code,
    nameUk: plan.nameUk,
    nameEn: plan.nameEn,
    descriptionUk: plan.descriptionUk,
    descriptionEn: plan.descriptionEn,
    priceMonthly: Number(plan.priceMonthly),
    priceYearly: plan.priceYearly ? Number(plan.priceYearly) : null,
    currency: plan.currency,
    maxXmlLimit: plan.maxXmlLimit,
    aiCredits: plan.aiCredits,
    canCloudBackup: plan.canCloudBackup,
    maxFeedsLimit: plan.maxFeedsLimit ?? 1,
    maxChannelsLimit: plan.maxChannelsLimit ?? 1,
    syncFrequencyHours: plan.syncFrequencyHours ?? 0,
    maxStorageGb: plan.maxStorageGb ? Number(plan.maxStorageGb) : 0,
    maxTeamSeats: plan.maxTeamSeats ?? 1,
    hasApiAccess: plan.hasApiAccess ?? false,
    hasWebhooks: plan.hasWebhooks ?? false,
    hasFeedDiff: plan.hasFeedDiff ?? false,
    hasWhiteLabel: plan.hasWhiteLabel ?? false,
    hasSso: plan.hasSso ?? false,
    hasAuditLog: plan.hasAuditLog ?? false,
    hasCustomS3: plan.hasCustomS3 ?? false,
    hasPriorityAi: plan.hasPriorityAi ?? false,
    slaUptimePercent: plan.slaUptimePercent ?? null,
    isPopular: plan.isPopular,
    isActive: plan.isActive,
    order: plan.order,
    durationDays: plan.durationDays,
    featuresUk: plan.featuresUk,
    featuresEn: plan.featuresEn,
    createdAt: plan.createdAt,
    updatedAt: plan.updatedAt,
  };
}
