import type {
  GrowthShowcaseConfig,
  RevenueGrowthPoint,
  AiActionLogItem,
  FunnelStageItem,
  LiveOrderItem,
} from '@/modules/growth-showcase/types';

export const DEFAULT_TIMELINE: RevenueGrowthPoint[] = [
  {
    monthKey: 'm1',
    monthLabelUk: 'Міс. 1 (Ручний старт)',
    monthLabelEn: 'Mo. 1 (Manual Start)',
    revenue: 45000,
    profit: 12500,
    ordersCount: 48,
    activeMarketplaces: 1,
  },
  {
    monthKey: 'm2',
    monthLabelUk: 'Міс. 2 (+Prom & Rozetka)',
    monthLabelEn: 'Mo. 2 (+Prom & Rozetka)',
    revenue: 135000,
    profit: 42000,
    ordersCount: 145,
    activeMarketplaces: 2,
  },
  {
    monthKey: 'm3',
    monthLabelUk: 'Міс. 3 (AI Оптимізація)',
    monthLabelEn: 'Mo. 3 (AI Optimization)',
    revenue: 290000,
    profit: 96000,
    ordersCount: 310,
    activeMarketplaces: 3,
  },
  {
    monthKey: 'm4',
    monthLabelUk: 'Міс. 4 (+Epicentr)',
    monthLabelEn: 'Mo. 4 (+Epicentr)',
    revenue: 440000,
    profit: 152000,
    ordersCount: 480,
    activeMarketplaces: 4,
  },
  {
    monthKey: 'm5',
    monthLabelUk: 'Міс. 5 (Масштабування)',
    monthLabelEn: 'Mo. 5 (Full Scale)',
    revenue: 585000,
    profit: 204000,
    ordersCount: 640,
    activeMarketplaces: 4,
  },
];

export const DEFAULT_AI_ACTIONS: AiActionLogItem[] = [
  {
    id: 'act-1',
    timestampText: '0.4s',
    textUk: 'AI автономно обробив 10 240 SKU постачальника без помилок',
    textEn: 'AI processed 10,240 supplier SKUs autonomously with 0 errors',
    tagUk: 'Каталог',
    tagEn: 'Catalog',
    category: 'ingestion',
  },
  {
    id: 'act-2',
    timestampText: '1.2s',
    textUk: 'AI згенерував переконливі SEO-описи та атрибути під Rozetka',
    textEn: 'AI generated persuasive SEO titles & attributes for Rozetka',
    tagUk: 'SEO & Тексти',
    tagEn: 'SEO & Copy',
    category: 'seo',
  },
  {
    id: 'act-3',
    timestampText: '2.1s',
    textUk: 'AI виставив динамічну маржу +28% проти демпінгу конкурентів',
    textEn: 'AI applied dynamic +28% margin protection against competitor dumping',
    tagUk: 'Ціноутворення',
    tagEn: 'Pricing',
    category: 'pricing',
  },
  {
    id: 'act-4',
    timestampText: '3.0s',
    textUk: 'Синхронізовано залишки та ціни на Rozetka, Prom та Epicentr',
    textEn: 'Synchronized stock & prices across Rozetka, Prom, and Epicentr',
    tagUk: 'Синхронізація',
    tagEn: 'Sync',
    category: 'sync',
  },
];

export const DEFAULT_STAGES: FunnelStageItem[] = [
  {
    id: 'prep',
    stepNumber: 1,
    titleUk: 'AI Підготовка товарів',
    titleEn: 'AI Product Preparation',
    subtitleUk: '10 000+ SKU за секунди',
    subtitleEn: '10,000+ SKUs in seconds',
    badgeUk: 'Автопілот',
    badgeEn: 'Autopilot',
    iconName: 'PackageCheck',
    statPrimaryUk: '10 240 SKU',
    statPrimaryEn: '10,240 SKUs',
    statSecondaryUk: '0 ручної роботи',
    statSecondaryEn: '0 manual work',
  },
  {
    id: 'sync',
    stepNumber: 2,
    titleUk: 'Синхронізація маркетплейсів',
    titleEn: 'Marketplace Sync',
    subtitleUk: 'Rozetka, Prom, Epicentr',
    subtitleEn: 'Rozetka, Prom, Epicentr',
    badgeUk: 'Multi-Channel',
    badgeEn: 'Multi-Channel',
    iconName: 'Rocket',
    statPrimaryUk: '4 канали',
    statPrimaryEn: '4 Channels',
    statSecondaryUk: '100% наявність',
    statSecondaryEn: '100% in-stock',
  },
  {
    id: 'revenue',
    stepNumber: 3,
    titleUk: 'Вибуховий ріст у грошах',
    titleEn: 'Exponential Revenue Growth',
    subtitleUk: '+430% чистий прибуток',
    subtitleEn: '+430% Net Profit',
    badgeUk: 'Масштаб',
    badgeEn: 'Scale',
    iconName: 'TrendingUp',
    statPrimaryUk: '₴585 000 / міс',
    statPrimaryEn: '$15,800 / mo',
    statSecondaryUk: '₴204 000 прибуток',
    statSecondaryEn: '$5,500 profit',
  },
];

export const DEFAULT_ORDERS: LiveOrderItem[] = [
  {
    id: 'ord-1',
    marketplace: 'Rozetka',
    productTitleUk: 'Смарт-годинник AMOLED Pro (2 шт)',
    productTitleEn: 'Smart Watch AMOLED Pro (2 pcs)',
    amount: 3450,
    timeAgoUk: 'щойно',
    timeAgoEn: 'just now',
  },
  {
    id: 'ord-2',
    marketplace: 'Prom',
    productTitleUk: 'Набір бездротових інструментів Max',
    productTitleEn: 'Wireless Power Tool Kit Max',
    amount: 4890,
    timeAgoUk: '1 хв тому',
    timeAgoEn: '1m ago',
  },
  {
    id: 'ord-3',
    marketplace: 'Epicentr',
    productTitleUk: 'Інверторний генератор 3.5 кВт',
    productTitleEn: 'Inverter Generator 3.5 kW',
    amount: 14200,
    timeAgoUk: '2 хв тому',
    timeAgoEn: '2m ago',
  },
];

export const DEFAULT_SHOWCASE_CONFIG: GrowthShowcaseConfig = {
  autoPlay: true,
  cycleIntervalMs: 3200,
  timeline: DEFAULT_TIMELINE,
  aiActions: DEFAULT_AI_ACTIONS,
  stages: DEFAULT_STAGES,
  recentOrders: DEFAULT_ORDERS,
};
